#!/usr/bin/env bash
# install and configures nginx

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw enable
sudo ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
