#!/usr/bin/env bash
#Configures an Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw enable
sudo ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

replacement="server_name _;\n\trewrite /redirect_me https://https://www.youtube.com/results?search_query=fashion;"
sudo sed -i "s|server_name _;|$replacement|" /etc/nginx/sites-available/default
