#!/usr/bin/env bash
# Configures an NGINX server on a brand new ubuntu machine.
# shellcheck disable=SC2154

sudo apt-get update
sudo apt-get install -y nginx
sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

hostname=$(hostname)

cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    add_header X-Served-By $hostname;

    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 http://pecjaneblog.tech/;
    }
    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}
EOF

# Restart Nginx to apply the changes
sudo service nginx restarti
