#!/usr/bin/env bash
# Installs and configures HAproxy loadbalancer.
# sudo apt-get install --no-install-recommends software-properties-common -y

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y install haproxy=2.9.\*
sudo chown -R $USER:$USER /etc/haproxy/
sudo apt-get -y update
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo  "
frontend myfrontend
	bind *:80
	mode http
	default_backend myservers
backend myservers
	balance roundrobin
	server 335870-web-01 54.157.154.219:80 check
	server 335870-web-02 52.91.148.7.3:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start

