#!usr/bin/env bash
#Your SSH client configuration must be configured to use the private key ~/.ssh/school
Host ubuntu
        HostName 54.157.154.219
        IdentityFile ~/.ssh/school
        PasswordAuthentication no
